### ISSUE TITLE
error on pipeline upload

### ISSUE THREAD

**Issue by dzerrenner** [pypyr-scheduler/pypyr-scheduler-server#4]
**Describe the bug**
While uploading a pipeline with the `--enable-upload` switch on, a pipeline gets not saved on the filesystem.

**To Reproduce**
1. Start development server with `--enable-upload`
2. Upload a pipeline file via the swagger ui console
3. Look at the (default) `pipelines`directory for the uploaded file.

**Expected behavior**
Pipeline was uploaded and saved to the file system.

```
DEBUG:connexion.decorators.validation:http://localhost:5000/pipelines/pipeline_now.yaml validating parameters...
DEBUG:connexion.decorators.parameter:Function Arguments: ['filename', 'body']
INFO:pyrsched.api.pipelines:POST /pipelines/pipeline_now.yaml
INFO:pyrsched.api.pipelines:saving file contents to /home/dzerrenn/projects/pypyr-scheduler/pipelines/pipeline_now.yaml
ERROR:pyrsched.app:Exception on /pipelines/pipeline_now.yaml [POST]
Traceback (most recent call last):
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/connexion/decorators/validation.py", line 165, in wrapper
    response = function(request)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/connexion/decorators/validation.py", line 339, in wrapper
    return function(request)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/home/dzerrenn/.local/share/virtualenvs/pypyr-scheduler-UBNwg3Am/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/home/dzerrenn/projects/pypyr-scheduler/pyrsched/api/pipelines.py", line 55, in create
    return _save_file(filename, body)
  File "/home/dzerrenn/projects/pypyr-scheduler/pyrsched/api/pipelines.py", line 44, in _save_file
    content.save(str(target))
AttributeError: 'bytes' object has no attribute 'save'
DEBUG:connexion.apis.flask_api:Getting data and status code
DEBUG:connexion.apis.flask_api:Got data and status code (500)
INFO:werkzeug:127.0.0.1 - - [12/Dec/2019 08:43:51] "POST /pipelines/pipeline_now.yaml HTTP/1.1" 500 -
```

**Comment by dzerrenner** [comment]
Feature was removed, resolved with #13
